# Site settings
title: RDMO
description: "Research Data Management Organiser"
baseurl: "rdmorganiser.github.io"
url: "https://mypydavid.github.io"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
- "vendor"
- "Gemfile*"
- "Makefile*"
- "README.md"

sass:
  style: :compressed
