# Site settings
title: RDMO
description: ""
baseurl: ""
url: "http://rdmorganiser.github.io"

# Build settings
markdown: kramdown
permalink: pretty

navitems:
  index:
    label:
      de: Projekt
      en: Project
    path:
      de: /
      en: /en
  workpackages:
    label:
      de: Arbeitspakete
      en: Work packages
    path:
      de: /arbeitspakete
      en: /en/workpackages
  networking:
    label:
      de: Vernetzung
      en: Outreach
    path:
      de: /vernetzung
      en: /en/outreach
  cooperations:
    label:
      de: Kooperationen
      en: Cooperations
    path:
      de: /kooperationen
      en: /en/cooperations
  team:
    label:
      de: Team
      en: Team
    path:
      de: /team
      en: /en/team
